services:
  red:
    build:
      context: ./red
    ports:
      # Syntax: "HOST_PORT:CONTAINER_PORT"
      - "4141:4141"
    volumes:
      - "./red:/app"
      - "red_node_modules:/app/node_modules" # exclude from volumes
    networks:
      - express-net

  green:
    build:
      context: ./green
    ports:
      - "7171:9191"
    volumes:
      - "./green:/app"
      - "green_node_modules:/app/node_modules" # exclude from volumes
    networks:
      - express-net

#  to communicate with each other via their service names (as hostnames)
networks:
  express-net:
    driver: bridge

volumes:
  green_node_modules:
    driver: local
  red_node_modules:
    driver: local